version: '3.8'
services:

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es01-test
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kib01-test
    networks:
      - elastic
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es01-test:9200

networks:
  elastic: