version: '3.8'
services:

  elastic-search:
    image: elasticsearch:8.5.1
    container_name: eslastic01
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ELASTIC_PASSWORD=MY_PASSWORD
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=65%
      - cluster.routing.allocation.disk.watermark.high=70%
      - xpack.security.audit.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    
  kibana:
    image: kibana:8.5.1
    container_name: kibana01
    networks:
      - elastic
    ports:
      - 5601:5601
    depends_on:
      - elastic-search

networks:
  elastic: