version: '3.8'
services:

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: eslastic01
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ELASTIC_PASSWORD=MY_PASSWORD
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=65%
      - cluster.routing.allocation.disk.watermark.high=70%
      - xpack.security.enabled=true
      - xpack.security.audit.enabled=true
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana01
    networks:
      - elastic
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://eslastic01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=MY_PASSWORD

networks:
  elastic: