version: '3.8'
services:

  elastic-search:
    image: elasticsearch:8.5.1
    container_name: eslastic01
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    
  kibana:
    image: kibana:8.5.1
    container_name: kibana01
    networks:
      - elastic
    ports:
      - 5601:5601
    depends_on:
      - elastic-search
    environment:
      - ELASTICSEARCH_HOSTS=http://eslastic01:9200

networks:
  elastic: